### ISSUE TITLE
BUG on Score Counting

### ISSUE THREAD

**Issue by tommix626** [muneck/MUNECK#32]
![image](https://user-images.githubusercontent.com/85062819/165794665-0d2ce402-b4dd-4a03-b920-db9d453dc439.png)
Though the performance is correctly calculated, it is not counted into score.

**Comment by tommix626** [comment]
![image](https://user-images.githubusercontent.com/85062819/165795132-583748a7-75b8-445b-b7fb-1ff2af1cef86.png)
The problem is here, the `individual_node_score` is not initialized. @KevDevPython 

#### But when return to main menu and come back again the scoring system go back to normal.

Hypothesis: Somthing wrong with tick sequence, or data not read before calculation happens.

**Comment by tommix626** [comment]
@KevDevPython  Please fix this on the newest merge of PR from MusicLoader branch to development.(create a fix-bug branch and submit a PR after fixing, or just fix it directly on development and push to origin. Both OK)

**Comment by SourceDevKev** [comment]
fixed
