### ISSUE TITLE
Add GI variable

### ISSUE THREAD

**Issue by William0830** [muneck/MUNECK#39]
add GI variable: deltaScore and Combo

**Comment by tommix626** [comment]
Got it, will add it afterwards.
If possible, make a int variable in CoreGamePlayGI under Content/Blueprint/.../CoreGamePlay/
and use it in UI widget for now.


发件人: William0830 ***@***.***>
发送时间: Monday, May 2, 2022 6:26:15 PM
收件人: muneck/MUNECK ***@***.***>
抄送: Subscribed ***@***.***>
主题: [muneck/MUNECK] Add GI variable (Issue #39)


add GI variable: deltaScore and Combo

―
